### ISSUE TITLE
Install fails on rpmlib

### ISSUE THREAD

**Issue by IchBin** [EmixamPP/synology-drive#1]
Will admit my linux skills are average. Not a seasoned admin here. Here's what happens when I try to run:
`sudo dnf localinstall synology-drive-3.1.0-12923.x86_64.rpm`

Distro - Centos 7.9

Running transaction check
Error: transaction check vs depsolve:
rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by synology-drive-3.1.0-12923.fc35.x86_64
To diagnose the problem, try running: 'rpm -Va --nofiles --nodigest'.
You probably have corrupted RPMDB, running 'rpm --rebuilddb' might fix the issue.
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.

**Comment by EmixamPP** [comment]
Sorry for the late reply. I will update the readme at the end of the week, to give instructions for compiling the .rpm locally.

**Comment by EmixamPP** [comment]
I took some time this morning to do it. The readme has been updated, you can check out the "Method 2". Feel free to ask me if you have a problem. I'll let you close the issue.
