### ISSUE TITLE
Rocky Linux 8.7 package

### ISSUE THREAD

**Issue by abelmilanes** [EmixamPP/synology-drive#11]
Any way of getting this to work on Rocky 8.7 / Gnome.
Thanks!

**Comment by EmixamPP** [comment]
Could you please share some details about your issue?

**Comment by EmixamPP** [comment]
Are you talking about the COPR repo?

**Comment by abelmilanes** [comment]
yes... `dnf install ` cannot find a package for Rocky 8.

**Comment by EmixamPP** [comment]
Fedora COPR does not offer to possibility to build against Rocky. You have to download manually a .rpm in the builds section on COPR ([for example, here, it is the build for fedora 39 (it should also work with Rocky)](https://download.copr.fedorainfracloud.org/results/emixampp/synology-drive/fedora-39-x86_64/06516200-synology-drive/)

**Comment by abelmilanes** [comment]
Thanks @EmixamPP that worked!
