### ISSUE TITLE
Changelog with bad date

### ISSUE THREAD

**Issue by spreiter** [EmixamPP/synology-drive#16]
Hi,

I tried to build it myself on Rocky 8 and found the following minor issue:

```
$ rpmbuild -ba synology-drive-noextra.spec
error: bad date in %changelog: Wed October 11 2023 Maxime Dirksen <dev@emixam.be> - 3.4.0-15721
```

Apparently the month is only allowed to have 3 letters. After I applied this in two lines, it ran through.

**Comment by EmixamPP** [comment]
I've pushed a fix. Thanks!
