### ISSUE TITLE
Cannot connect with NAS - insufficient user priviliges

### ISSUE THREAD

**Issue by michib-xx** [EmixamPP/synology-drive#19]
I'm using Fedora 40. When I want to connect to my NAS, I get the error "invalid username/password or insufficient user privilege." 

However, I'm using Drive with Windows clients with the same user/pwd successfully. I've already de- and re-activated the Drive app rights in DSM (7.2) for my user.

Starting the app with sudo doesn't help either. 

Any hints?

**Comment by EmixamPP** [comment]
I do not think this is related to the packaging of the app. I have no control over whatsoever. 

Maybe try to write your username password in clear then copy and paste then, in order to be sure that there is no mistake. Otherwise, I have no clue

**Comment by michib-xx** [comment]
Just found some hints in other threads: the linux drive client cannot handle symbols in passwords. I confirmed  this: login works if password only contains letters and digits. 

This is a shame!
