### ISSUE TITLE
Possible Beta build?

### ISSUE THREAD

**Issue by drohm** [EmixamPP/synology-drive#2]
Would it be possible to get a beta build for this?  The 3.2.0.13181 beta has been out for a bit and I'd love to test this out on Fedora36 and eventually Fedora37.

The beta can be downloaded here (similar url to standard releases):
https://global.download.synology.com/download/Utility/SynologyDriveClient/3.2.0-13181/Ubuntu/Installer/x86_64/synology-drive-client-13181.x86_64.deb

Thanks for making these installers available.

**Comment by drohm** [comment]
I was able to follow the instructions and get a beta build done and installed, working great so far.  Out of curiousity, how'd you get all the other builds you list in the releases page?  Did you do separate builds for each distro?

**Comment by EmixamPP** [comment]
The COPR platform builds the rpm package for each x86 distro. Then I just take the time to download them all by exploring the build result.

Regarding the question, will I put the beta on the COPR repo, the answer is no. Because everyone will get the update and since the package may not be stable, I prefer not to force everyone to use it.

**Comment by drohm** [comment]
Oh, I wasn't aware the client would auto-update non-beta versions.  Makes sense, thanks!

**Comment by drohm** [comment]
I meant more the client, but to your point, we haven't added a repository for dnf to search for updates, so how would dnf update the app?

**Comment by EmixamPP** [comment]
I provide a repository through fedora COPR, as mentioned by the [method 1 of the readme](https://github.com/EmixamPP/synology-drive#method-1-install-from-copr-repo-recommended-to-get-updates]) 

Moreover, I've disabled auto update of synology-drive-client for many reasons ...

**Comment by drohm** [comment]
But as an end-user, I haven't configured the repository on my machine.  I simply installed the appropriate .rpm.  If I were to do a dnf upgrade it doesn't have the repository configured to check updates.
