### ISSUE TITLE
fc37 no context menu/overlay icons

### ISSUE THREAD

**Issue by cedricbrx** [EmixamPP/synology-drive#3]
Hi,

Just installed your package the first time.
Everything went well, except that i didn't got the context menu/overlay icons in nautilus

Best regards,

**Comment by EmixamPP** [comment]
Did you install the `synology-drive` version ? Because the `synology-drive-noextra` version doesn't contain this feature.

**Comment by cedricbrx** [comment]
Yes i did install the synology-drive version,

**Comment by cedricbrx** [comment]
Hello, might be not a problem with your package but a problem with the synology package as i'm not getting any overlay icon with the official package and ubuntu 22.10

**Comment by EmixamPP** [comment]
Personally, I don't have this problem. 

Are you sure you are on a synchronized drive folder? The context menu only appears on these files. Moreover, it doesn't appear if Synology-drive is not running, nor if it is not connected to the server (network issue, etc.).

**Comment by EmixamPP** [comment]
Can you verify if the `/usr/lib64/nautilus/extensions-3.0/libnautilus-drive-extension.so` is present, as well as the `nautilus-extensions` package ?

If so, you can try to execute `sudo chmod a+x /usr/lib64/nautilus/extensions-3.0/libnautilus-drive-extension.so`. Maybe add the execute permission to the nautilus extension will solve the issue.

**Comment by cedricbrx** [comment]
> Personally, I don't have this problem.
> 
> Are you sure you are on a synchronized drive folder? The context menu only appears on these files. Moreover, it doesn't appear if Synology-drive is not running, nor if it is not connected to the server (network issue, etc.).

Yes i am sure, synology drive is running, connected and i am looking at the right folders

**Comment by cedricbrx** [comment]
/usr/lib64/nautilus/extensions-3.0/libnautilus-drive-extension.so is present and has the exexute permission
Are you using fedora 37 or ubuntu 22.10 as both have nautilus 43, i didn't had any problems with ubuntu 22.04
Maybe the problem is that synology has not released a version compatible with nautilus 43

**Comment by EmixamPP** [comment]
I'm waiting for the final release to switch to Fedora 37. 

Indeed, nautilus 43 has switched to gtk4 (libadwaita). And maybe this i why the extension may not work any more.

We should open a ticket to the Synology helpdesk.

**Comment by cedricbrx** [comment]
from synology:

**Yes the developers confirmed this:

According to the Release Notes of ubuntu 22.10, Nautilus will be upgraded to GTK4 on 22.10, then related extension functions will fail.

(Icon overlay belongs to Nautilus extension, compatibility problem)

Sadly for the moment there is no workaround, the developers are working to fix the issue in the next release**

Best Regards,

**Comment by EmixamPP** [comment]
The v3.2.1-13271 has been released today. I have made the necessary modifications and pushed the new version on the COPR repo. They are being built. You should be able to update it soon. Let me know if everything works.

**Comment by 8johnny6** [comment]
Hey @EmixamPP, 
thanks for your effort. I've had the same problem since the update to f37. Now with version v3.2.1-13271 installed everything works fine; contextmenu, Iconoverlay. Just perfect. i love it. 

Thanks
