### ISSUE TITLE
Context menu for KDE Dolphin?

### ISSUE THREAD

**Issue by schM0ggi** [EmixamPP/synology-drive#4]
Hi,

thanks for this awesome package. It's a shame Synology doesn't provide an official rpm.

I'm using Fedora with KDE and I've installed your package with the "no extra" variant.
Question: Is it possible to get Synology Drive functions via the context menu in Dolphin?

Edit:
Just realized that things like "on demand sync" are absent. It synced my complete home folder from my NAS locally.
Am I doing something wrong or is it because I'm on KDE? Sadly, in this state it's not useful at all :/.

Thank you!

**Comment by EmixamPP** [comment]
> Is it possible to get Synology Drive functions via the context menu in Dolphin?

Unfortunately, Synology only built a pluggin for the Nautilus API. Therefore, unless they also do it for Dolphin. I can't do anything about it. 

> Just realized that things like "on demand sync" are absent.

Indeed, on demande sync is disabled even on Ubuntu. And I think that such feature is very hard to implement on Linux. Even Nextcloud only support that on Windows.

**Comment by EmixamPP** [comment]
Sorry I couldn't help you! 
I'm closing the issue, but feel free to comment to reopen it if needed.
